package:
  name: matumap
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/zekearneodo/matumap.git

requirements:
  build:
    - python
    - setuptools
    - umap-learn >=0.3.7 <=0.4
  run:
    - python
    - umap-learn >=0.3.7 <=0.4

test:
  imports:
    - matumap

about:
  home: https://github.com/zekearneodo/matumap
  license: BSD
  license_file: LICENSE