package:
  name: matumap
  version: "0.0.2"

source:
  git_rev: v0.0.2
  git_url: https://github.com/zekearneodo/matumap.git

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.4
    - umap-learn >=0.3
  run:
    - {{ pin_compatible('python', max_pin='x.x.x') }}
    - numpy >=1.4
    - umap-learn >=0.3

test:
  imports:
    - matumap

about:
  home: https://github.com/zekearneodo/matumap
  license: BSD